version: '3.7'

services:

  qnap_exporter:
    container_name: qnap_exporter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2003:2003"
      - "1805:1805"
    environment:
      # like `10.0.1.1` or `qnap`
      - QNAP_HOST_IP=${QNAP_NAS_IP}
      # like `admin` or `jordan`
      - QNAP_USERNAME=${QNAP_NAS_USERNAME}
      # hopefully something secret!
      - QNAP_PASSWORD=${QNAP_NAS_PASSWORD}
#      - SHOULD_SCHEDULE_QNAP_METRICS_UPDATES=0
    stdin_open: true
    tty: true
