version: '3.7'

services:

  qnap_exporter:
    container_name: qnap_exporter
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sh', 'run_prod.sh' ]
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2003:2003"
      - "1805:1805"
    environment:
      - QNAP_HOST_IP=10.0.1.1
      - QNAP_USERNAME=admin
      - QNAP_PASSWORD=password
    stdin_open: true
    tty: true
