nas_instances:
  - nas_name: solaris NAS
    nas_host: 10.0.1.62
    nas_port: 8080
    nas_username: gurooj
    nas_password: cxf1tbn0jhp4yma_GUJ

  - nas_name: foo NAS
    nas_host: 10.0.1.222
    nas_port: 8080
    nas_username: admin
    nas_password: bar
